version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  studentsdb:
    networks:
      - backend
    image: mongo:latest
    container_name: studentsdb
    ports:
      - 27017:27017
  student-app-image:
    networks:
      - backend
    image: student-app-image
    container_name: student-app-image
    ports:
      - 8080:8080
    links:
      - studentsdb